#This file contains configuration information for each Cimpress IO service endpoint.
 services:
  staging_print_fulfillment_api:
    client_id: 4GtkxJhz0U1bdggHMdaySAy05IV4MEDV
    health_check_url: https://api.cimpress.io/v1/livecheck
    endpoint_url: https://api.cimpress.io/swagger/sandbox/vcs/printapi/v1/
  barcode_image_creator:
    client_id: lsbRM318dQg5W6yUBW9m8K0hPM9Qg1Uw
    health_check_url: https://barcode.at.cimpress.io/v1/healthcheck
    endpoint_url: https://barcode.at.cimpress.io/v1/
  rasterization:
    client_id: 3Y3QAMHT1CQYaCTtuyhymxfBcznVoZN9
    health_check_url: https://rasterization.prepress.documents.cimpress.io/status/healthcheck
    endpoint_url: https://rasterization.prepress.documents.cimpress.io/rasterize/v1/
  file_storage_and_preview_generation:
    client_id: WuPUpCSkomz4mtPxCIXbLdYhgOLf4fhJ
    health_check_url:
    endpoint_url: https://uploads.documents.cimpress.io/v1/uploads